### ISSUE TITLE
Make Cluster.k8s.ionoscloud.crossplane.io return token and server Url 

### ISSUE THREAD

**Issue by Syndlex** [ionos-cloud/crossplane-provider-ionoscloud#116]
### What problem are you facing?
We try to setup a cluster and connect it with argocd. The Problem we are facing is that the connection Details return the config to connect to the cluster. 
I haven't found a way to extract the needed values.

### How could Crossplane Provider IONOS Cloud help solve your problem?

It would be nice if the connection Details secret would have a field for server Url and the api token.

**Comment by cristiGuranIonos** [comment]
Released 1.0.7, thanks for the PRs!
