### ISSUE TITLE
user and other endpoints

### ISSUE THREAD

**Issue by Syndlex** [ionos-cloud/crossplane-provider-ionoscloud#119]
What is the state of this provider?
There are a lot of missing objects like the s3 user key stuff... 
Are there any plans to add these and bring the Provider to a usable state Similar to terraform.

I talked with some IONOS engineers at the IONOS Summit about this provider. would be create to see more functionality

**Comment by cbeti-ionos** [comment]
Hi, there have been quite a few objects added to the provider since, such as the NLB resources, compute users/groups, s3 user key and so on. 
The provider is actively maintained so if there's anything missing that you'd like to see added, open an issue and we'll start working on it.
