### ISSUE TITLE
publish in upbound marketplace

### ISSUE THREAD

**Issue by haarchri** [ionos-cloud/crossplane-provider-ionoscloud#143]
### What problem are you facing?
Have you considered publishing this provider on the Upbound Marketplace? If so, please reach out on the Crossplane Slack, and we can begin the publication process

https://marketplace.upbound.io/

**Comment by cristiGuranIonos** [comment]
Thanks for the suggestion!

**Comment by haarchri** [comment]
provider is published: https://marketplace.upbound.io/providers/ionoscloud/provider-ionoscloud/
