### ISSUE TITLE
Request to add Argo resource health checks for Ionos resources

### ISSUE THREAD

**Issue by leroyshirto** [ionos-cloud/crossplane-provider-ionoscloud#199]
Please may you look into contributing resource health checks to the ArgoCD project for the resources provided by this provider?
At present if you use Argo to manage your crossplane resources, they will all show as healthy even if they are currently failing. Argo provides a mechanism for third parties to submit custom resource health checks, see https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#way-2-contribute-a-custom-health-check

The Argo repo contains examples of health checks for other crossplane providers see https://github.com/argoproj/argo-cd/tree/master/resource_customizations

Thanks

**Comment by cbeti-ionos** [comment]
Hello, this is now currently in the works, however if you'd like to have health checks for the ionoscloud resources available in Argocd in the meantime, the `argo-cd` ConfigMap can be edited as shown [here](https://docs.crossplane.io/latest/guides/crossplane-with-argo-cd/#set-health-status).

I've also created this [PR](https://github.com/ionos-cloud/crossplane-provider-ionoscloud/pull/229) for ArgoCD usage examples where I add the health checks as a value for the argocd helm chart. The ionoscloud resources created here all have tracking and health checks enabled.

**Comment by cbeti-ionos** [comment]
It seems bundling health checks for managed resources is not something other providers do. One of the reasons for this is that Claims or Composite resources don't inherit their health state.
Managed Resources are also fully covered by the script provided in the Crossplane docs so it's probably better if users include these as settings of their Argocd installation.
