### ISSUE TITLE
Support publishConnectionDetailsTo

### ISSUE THREAD

**Issue by mcbenjemaa** [ionos-cloud/crossplane-provider-ionoscloud#221]
### What problem are you facing?

Our provider doesn't support the feature `publishConnectionDetailsTo` provided by crossplane.

### How could Crossplane Provider IONOS Cloud help solve your problem?

We need `publishConnectionDetailsTo` to support onboarding of dataplane clusters.

`publishConnectionDetailsTo` can enable users to add metadata to the Secret.

**Comment by dhermann-ionos** [comment]
We would already benefit from the basic use case, i.e., to write into a Kubernetes secret locally, with custom labels and annotations. The key benefit is the ability to add metadata, which is not possible when using _writeConnectionSecretToRef_.
